name: 'Setup MSYS2'
description: 'Setup an MSYS2 environment'
branding:
  color: purple
  icon: terminal
inputs:
  msystem:
    description: 'Variant of the environment to set by default: MSYS, MINGW32 or MINGW64'
    required: false
    default: 'MINGW64'
  path-type:
    description: 'Default value for MSYS2_PATH_TYPE environment variable: strict, inherit or minimal'
    required: false
    default: 'minimal'
  release:
    description: 'Retrieve and extract base installation from upstream GitHub Releases'
    required: false
    default: true
  update:
    description: 'Update MSYS2 installation through pacman'
    required: false
    default: false
  install:
    description: 'Install packages after installation through pacman'
    required: false
    default: false
  bitness:
    description: 'Bitness of MSYS2: 32 or 64 (advanced users only)'
    required: false
    default: '64'
outputs:
  msysRootDir:
    description: 'Path to the MSYS root'
runs:
  using: 'node12'
  main: 'index.js'
