name: 'Setup MSYS2'
description: 'Setup an MSYS2 environment'
branding:
  color: purple
  icon: terminal
inputs:
  msystem:
    description: 'Variant of the environment to set by default: MSYS, MINGW32, MINGW64, UCRT64, CLANG32, CLANG64 or CLANGARM64'
    required: false
    default: 'MINGW64'
  path-type:
    description: 'Default value for MSYS2_PATH_TYPE environment variable: strict, inherit or minimal'
    required: false
    default: 'minimal'
  update:
    description: 'Update MSYS2 installation through pacman'
    required: false
    default: false
  install:
    description: 'After installation and/or update, install additional packages through pacman'
    required: false
    default: false
  pacboy:
    description: 'After installation and/or update, install additional packages through pacboy'
    required: false
    default: false
  bitness:
    description: 'Bitness of MSYS2: 32 or 64 (advanced users only)'
    required: false
    default: '64'
  release:
    description: 'Retrieve and extract base installation from upstream GitHub Releases'
    required: false
    default: true
  location:
    description: 'Where to install MSYS2'
    required: false
    default: 'RUNNER_TEMP'
  platform-check-severity:
    description: 'What to do when run on an incompatible runner: fatal, warn'
    required: false
    default: 'fatal'
  cache:
    description: 'If caching should be used'
    required: false
    default: true
runs:
  using: 'node20'
  main: 'index.js'
