name: Example PKGBUILD

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:


  win-makepkg:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
          - { icon: '🟨', sys: ucrt64  } # Experimental!
          - { icon: '🟧', sys: clang64 } # Experimental!
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }} | makepkg
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.sys }}
    steps:

    - name: '⚙️ git config'
      run: git config --global core.autocrlf input
      shell: bash

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: git base-devel tree
        pacboy: toolchain:p

    - name: '🚧 Build package'
      run: |
        cd examples/pkgbuild
        makepkg-mingw --noconfirm --noprogressbar -sCLf

    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.sys }}-TOOL
        path: examples/pkgbuild/*.zst

    - name: '🔍 Show package content'
      run: |
        mkdir tmp
        cd tmp
        tar -xf ../examples/pkgbuild/*.zst
        tree .


  win-test:
    needs: win-makepkg
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
          - { icon: '🟨', sys: ucrt64  } # Experimental!
          - { icon: '🟧', sys: clang64 } # Experimental!
    name: 🚦${{ matrix.icon }} ${{ matrix.sys }} | test
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true

    - name: '📥 Download artifact: package'
      uses: actions/download-artifact@v2
      with:
        path: .
        name: ${{ matrix.sys }}-TOOL

    - name: '🛠️ Install package'
      run: pacman -U --noconfirm --noprogressbar *.zst

    - name: '🚦 Test package'
      run: TOOL
